### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by pretech86** [unk9vvn/AndTroj#2]
dear thanks for your ifort , i face the following error 

Traceback (most recent call last):
  File "./atj.py", line 6, in <module>
    from core.menu import main_menu
  File "/root/Downloads/2-undetectable payload generators/windows/AndTroj/core/menu.py", line 7, in <module>
    from core.binder import binder
  File "/root/Downloads/2-undetectable payload generators/windows/AndTroj/core/binder.py", line 7, in <module>
    from core.eng_menu import social_eng_menu
  File "/root/Downloads/2-undetectable payload generators/windows/AndTroj/core/eng_menu.py", line 6, in <module>
    from twilio.rest import Client
ImportError: No module named twilio.rest

**Comment by l14ck3r0x01** [comment]
install the twilio module by :

**Comment by pretech86** [comment]
i make it also the same problem

**Comment by l14ck3r0x01** [comment]
are you using the last version ?

**Comment by pretech86** [comment]
i solved it thanks but it give me a nother error 

Traceback (most recent call last):
  File "./atj.py", line 6, in <module>
    from core.menu import main_menu
  File "/root/Downloads/2-undetectable payload generators/windows/AndTroj/core/menu.py", line 7, in <module>
    from core.binder import binder
  File "/root/Downloads/2-undetectable payload generators/windows/AndTroj/core/binder.py", line 7, in <module>
    from core.eng_menu import social_eng_menu
  File "/root/Downloads/2-undetectable payload generators/windows/AndTroj/core/eng_menu.py", line 8, in <module>
    from lib.Web.Harvester import harstr
  File "/root/Downloads/2-undetectable payload generators/windows/AndTroj/lib/Web/Harvester.py", line 9, in <module>
    LAN = ([l for l in ([ip for ip in socket.gethostbyname_ex(socket.gethostname())[2]
NameError: name 'socket' is not defined

**Comment by l14ck3r0x01** [comment]
Actully i send a pull request for fix this error, you can get this one in my repo ... 
It is not have any error ...
Thank you for informing me about this issue.
