### ISSUE TITLE
some error while run atj.py

### ISSUE THREAD

**Issue by hardik-zinzuvadiya** [unk9vvn/AndTroj#4]
Traceback (most recent call last):
  File "./atj.py", line 6, in <module>
    from core.menu import main_menu
  File "/home/zinzu/AndTroj/core/menu.py", line 7, in <module>
    from core.binder import binder
  File "/home/zinzu/AndTroj/core/binder.py", line 7, in <module>
    from core.eng_menu import social_eng_menu
  File "/home/zinzu/AndTroj/core/eng_menu.py", line 8, in <module>
    from lib.Web.Harvester import harstr
  File "/home/zinzu/AndTroj/lib/Web/Harvester.py", line 9, in <module>
    LAN = ([l for l in ([ip for ip in socket.gethostbyname_ex(socket.gethostname())[2]
NameError: name 'socket' is not defined

**Comment by djhashh** [comment]
Ditto

**Comment by unk9vvn** [comment]
pls wait for updated Library API

**Comment by hustwyk** [comment]
Same question, wait for solution
