### ISSUE TITLE
Error modules HELP to fix it please 

### ISSUE THREAD

**Issue by amster699** [unk9vvn/AndTroj#5]
Hello im having this error on my kali linux 2019.3 everything goes smoth until i type ./atj.py .. how to fix this brother ?? whats the command sintax ??
root@kali:~/AndTroj# ./atj.py
Traceback (most recent call last):
  File "./atj.py", line 6, in <module>
    from core.menu import main_menu
  File "/root/AndTroj/core/menu.py", line 7, in <module>
    from core.binder import binder
  File "/root/AndTroj/core/binder.py", line 7, in <module>
    from core.eng_menu import social_eng_menu
  File "/root/AndTroj/core/eng_menu.py", line 8, in <module>
    from lib.Web.Harvester import harstr
  File "/root/AndTroj/lib/Web/Harvester.py", line 9, in <module>
    LAN = ([l for l in ([ip for ip in socket.gethostbyname_ex(socket.gethostname())[2]
NameError: name 'socket' is not defined

**Comment by elfnight0** [comment]
hi help me 
root@D4rkn3ss:~/AndTroj# ./atj.py 
Traceback (most recent call last):
  File "./atj.py", line 4, in <module>
    from core.start import start
  File "/root/AndTroj/core/start.py", line 118
    print "Kill PID: %s; Command: %s" % (pid, cmd)
                                    ^
SyntaxError: invalid syntax
root@D4rkn3ss:~/AndTroj# uname -a
Linux D4rkn3ss 5.3.0-kali3-amd64 #1 SMP Debian 5.3.15-1kali1 (2019-12-09) x86_64 GNU/Linux
root@D4rkn3ss:~/AndTroj#
